using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TechnineUzduotis.Classes.Enumerated
{
    public class EnumClass
    {
        public enum European
        {
            Albania = 20,
            Armenia = 20,
            Austria = 20,
            Belgium = 21,
            Bulgaria = 20,
            Croatia = 25,
            Cyprus = 19,
            Czechia = 21,
            Denmark = 25,
            Estonia = 20,
            Finland = 24,
            France = 20,
            Germany = 19,
            Greece = 24,
            Hungary = 27,
            Iceland = 23,
            Ireland = 23,
            Italy = 22,
            Latvia = 21,
            Lithuania = 21,
            Luxembourg = 17,
            Malta = 18,
            Monaco = 20,
            Netherlands = 21,
            Norway = 25,
            Poland = 23,
            Portugal = 23,
            RepublicofMoldova = 20,
            Romania = 19,
            Slovakia = 20,
            Slovenia = 22,
            Spain = 21,
            Sweden = 25,
            Switzerland = 8,
            Turkey = 18,
            Ukraine = 20,
            UnitedKingdomofGreatBritainandNorthernIreland = 20,
        }

        public enum CountryList
        {
            Andorra,
            UnitedArabEmirates,
            Afghanistan,
            AntiguaandBarbuda,
            Albania,
            Armenia,
            Angola,
            Argentina,
            Austria,
            Australia,
            Azerbaijan,
            BosniaandHerzegovina,
            Barbados,
            Bangladesh,
            Belgium,
            BurkinaFaso,
            Bulgaria,
            Bahrain,
            Burundi,
            Benin,
            BruneiDarussalam,
            Bolivia,
            Brazil,
            Bahamas,
            Bhutan,
            Botswana,
            Belarus,
            Belize,
            Canada,
            DemocraticRepublicoftheCongo,
            CentralAfricanRepublic,
            Congo,
            Switzerland,
            CôtedIvoire,
            Chile,
            Cameroon,
            China,
            Colombia,
            CostaRica,
            Cuba,
            CapeVerde,
            Cyprus,
            CzechRepublic,
            Germany,
            Djibouti,
            Denmark,
            Dominica,
            DominicanRepublic,
            Algeria,
            Ecuador,
            Estonia,
            Egypt,
            Eritrea,
            Spain,
            Ethiopia,
            Finland,
            Fiji,
            Micronesia,
            France,
            Gabon,
            UnitedKingdomofGreatBritainandNorthernIreland,
            Grenada,
            Georgia,
            Ghana,
            Gambia,
            Guinea,
            EquatorialGuinea,
            Greece,
            Guatemala,
            GuineaBissau,
            Guyana,
            Honduras,
            Croatia,
            Haiti,
            Hungary,
            Indonesia,
            Ireland,
            Israel,
            India,
            Iraq,
            Iran,
            Iceland,
            Italy,
            Jamaica,
            Jordan,
            Japan,
            Kenya,
            Kyrgyzstan,
            Cambodia,
            Kiribati,
            Comoros,
            SaintKittsandNevis,
            DemocraticPeoplesRepublicofKorea,
            RepublicofKorea,
            Kuwait,
            Kazakhstan,
            LaoPeoplesDemocraticRepublic,
            Lebanon,
            SaintLucia,
            Liechtenstein,
            SriLanka,
            Liberia,
            Lesotho,
            Lithuania,
            Luxembourg,
            Latvia,
            LibyanArabJamahiriya,
            Morocco,
            Monaco,
            RepublicofMoldova,
            Montenegro,
            Madagascar,
            MarshallIslands,
            TheformerYugoslavRepublicofMacedonia,
            Mali,
            Myanmar,
            Mongolia,
            Mauritania,
            Malta,
            Mauritius,
            Maldives,
            Malawi,
            Mexico,
            Malaysia,
            Mozambique,
            Namibia,
            Niger,
            Nigeria,
            Nicaragua,
            Netherlands,
            Norway,
            Nepal,
            Nauru,
            NewZealand,
            Oman,
            Panama,
            Peru,
            PapuaNewGuinea,
            Philippines,
            Pakistan,
            Poland,
            Portugal,
            Palau,
            Paraguay,
            Qatar,
            Romania,
            Serbia,
            RussianFederation,
            Rwanda,
            SaudiArabia,
            SolomonIslands,
            Seychelles,
            Sudan,
            Sweden,
            Singapore,
            Slovenia,
            Slovakia,
            SierraLeone,
            SanMarino,
            Senegal,
            Somalia,
            Suriname,
            SouthSudan,
            SaoTomeandPrincipe,
            ElSalvador,
            SyrianArabRepublic,
            Swaziland,
            Chad,
            Togo,
            Thailand,
            Tajikistan,
            TimorLeste,
            Turkmenistan,
            Tunisia,
            Tonga,
            Turkey,
            TrinidadandTobago,
            Tuvalu,
            UnitedRepublicofTanzania,
            Ukraine,
            Uganda,
            UnitedStatesofAmerica,
            Uruguay,
            Uzbekistan,
            SaintVincentandtheGrenadines,
            Venezuela,
            VietNam,
            Vanuatu,
            Samoa,
            Yemen,
            SouthAfrica,
            Zambia,
            Zimbabwe
        }
    }
}
